HeatTemplateFormatVersion: '2012-12-12'
Description: Key Server
Outputs:
  Name:
    Description: public DNS name of Instance
    Value:
      Fn::Select:
      - ip_address
      - Fn::Select:
        - '0'
        - Fn::GetAtt: [PrimaryInterface, fixed_ips]
  Id:
    Description: Instance Id
    Value:
      Ref: Instance
Parameters:
  IpAddress: {Description: Floating Ip Address to assign, Type: String}
  VolumeId: {Description: Volume where data lives, Type: String}
  PrimaryNetworkId: {Description: PrimaryNetworkId, Type: String}
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access, Type: String}
  ExtraUserData: {Default: '', Description: Extra
      UserData script, Type: String}
  InstanceZone: {Default: 'nova', Description: AvailabilityZone for
      this instance, Type: String}
  Flavor:
    Default: m1.tiny
    Description: Flavor to boot
    Type: String
  Image:
    Default: centos-6.5
    Description: Image of choice
    Type: String
  StartupTimeout: {Default: '1700', Description: How
      long to wait on node coming up, Type: Number}
  Name: 
    Description: Name of services in the stack
    Default: Mgmt
    Type: String
  EpelRepo: 
    Description: Yum repo for epel.
    Type: String
  KeyserverRepo: 
    Description: Yum repo where the keyserver lives.
    Type: String
Resources:
  PrimaryInterface:
    Properties:
      name:
        Fn::Join:
          - ''
          - - {Ref: Name}
            - '-PrimaryPort'
      network_id: {Ref: PrimaryNetworkId}
    Type: OS::Neutron::Port
  Instance:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              cryptsetup-luks: []
              mdadm: []
              lvm2: []
    Properties:
      name:
        Fn::Join:
          - ''
          - - {Ref: Name}
      availability_zone: {Ref: InstanceZone}
      image: {Ref: Image}
      flavor: {Ref: Flavor}
      key_name: {Ref: KeyName}
      networks:
        - {port: {Ref: PrimaryInterface}}
      user_data:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - "yum update -y aws-cfn-bootstrap\n"
            - "## Error reporting helper function\n"
            - "function error_exit\n"
            - "{\n"
            - "   /opt/aws/bin/cfn-signal -e 1 -r \"$1\" '"
            - {Ref: WaitHandleInstance}
            - "'\n"
            - "   exit 1\n"
            - "}\n"
            - "function trap_error\n"
            - "{\n"
            - "	error_exit \"Line: ${BASH_LINENO[0]}, ExitCode: $1\"\n"
            - "}\n"
            - "set -eu\n"
            - "trap 'trap_error \"$?\"' ERR\n"
            - "## Initialize CloudFormation bits\n"
            - "/opt/aws/bin/cfn-init -s "
            - {Ref: "AWS::StackName"}
            - " -r Instance --region "
            - {Ref: "AWS::Region"}
            - " > /tmp/cfn-init.log 2>&1 || error_exit $(</tmp/cfn-init.log)\n"
            - "KEYSERVERREPO="
            - {Ref: KeyserverRepo}
            - "\n"
            - "EPELREPO="
            - {Ref: EpelRepo}
            - "\n"
            - "if [ \"x$EPELREPO\" != \"x\" ]; then\n"
            - "  cat > /etc/yum.repos.d/keyserver.repo << EOF\n"
            - "[keyserverrepo]\n"
            - "name=keyserver repo\n"
            - "baseurl="
            - {Ref: KeyserverRepo}
            - "\n"
            - "failovermethod=priority\n"
            - "enabled=1\n"
            - "gpgcheck=0\n"
            - "EOF\n"
            - "fi\n"
            - "if [ \"x$EPELREPO\" != \"x\" ]; then\n"
            - "  cat > /etc/yum.repos.d/epel.repo << EOF\n"
            - "[epel]\n"
            - "name=epel repo\n"
            - "baseurl="
            - {Ref: EpelRepo}
            - "\n"
            - "failovermethod=priority\n"
            - "enabled=1\n"
            - "gpgcheck=0\n"
            - "EOF\n"
            - "fi\n"
            - "NAME="
            - {Ref: Name}
            - "\n"
            - "DEVICE=`blkid | grep crypto_LUKS | head -n 1 | awk -F: '{print $1}'`\n"
            - "echo \"$NAME\" $DEVICE | tee -a /etc/crypttab\n"
            - "echo \"/dev/mapper/$NAME /srv auto defaults,auto,noatime,noexec 0 0\""
            - " | tee -a /etc/fstab\n"
            - "yum install -y msc-keyserver crudini\n"
            - "chkconfig httpd off\n"
            - "cat > /etc/rc.firstboot <<\"EOF\"\n"
            - "if [ ! -f /srv/config/msckeys ]; then\n"
            - "  sed 's:@AUTH_KEY_CHANGEME@:'`dd if=/dev/random bs=1 count=9|base64`':' /etc/msckeys > /srv/config/msckeys\n"
            - "  crudini -set /srv/config/msckeys config gendersfile /srv/config/genders\n"
            - "  crudini -set /srv/config/msckeys serverkeypair publickeyfile /srv/config/msc-server-key.pub\n"
            - "  crudini -set /srv/config/msckeys serverkeypair privatekeyfile /srv/config/msc-server-key.pem\n"
            - "  crudini -set /srv/config/msckeys trustedkeypair publickeyfile /srv/config/msc-trusted-key.pub\n"
            - "  crudini -set /srv/config/msckeys trustedkeypair privatekeyfile /srv/config/msc-trusted-key.pem\n"
            - "fi\n"
            - "rm -f /etc/msckeys\n"
            - "if [ ! -f /srv/config/msc-server-key.pem ]; then\n"
            - "  mv /etc/msc-server-key.pub /srv/config/\n"
            - "  mv /etc/msc-server-key.pem /srv/config/\n"
            - "  mv /etc/msc-trusted-key.pub /srv/config/\n"
            - "  mv /etc/msc-trusted-key.pem /srv/config/\n"
            - "fi\n"
            - "rm -f /etc/msc-server-key.pub\n"
            - "rm -f /etc/msc-server-key.pem\n"
            - "rm -f /etc/msc-trusted-key.pub\n"
            - "rm -f /etc/msc-trusted-key.pem\n"
            - "ln -s /srv/config/msckeys /etc/\n"
            - "ln -s /srv/config/genders /etc/\n"
            - "touch /srv/config/genders\n"
            - "service httpd start\n"
            - "chkconfig httpd on\n"
            - "rm -f /etc/rc.firstboot\n"
            - "EOF\n"
            - "echo 'if [ -f /etc/rc.firstboot ]; then bash /etc/rc.firstboot; fi' >> /etc/rc.local\n"
            - "## Extra userdata\n"
            - {Ref: ExtraUserData}
            - "\n"
            - "mv /etc/ssh /etc/ssh.orig\n"
            - "ln -s /srv/config/ssh /etc/ssh\n"
            - "sed 's/\\(console=tty0\\)[ ]*\(.*\\)[ ]*\\(console=ttyS0,115200\\)/\\2 \\3 \\1/' /boot/syslinux/syslinux.cfg\n"
            - "## CloudFormation signal that setup is complete\n"
            - "/opt/aws/bin/cfn-signal -e 0 -r \"ConfigServer setup complete\" '"
            - {Ref: WaitHandleInstance}
            - "'\n"
            - "reboot\n"
    Type: OS::Nova::Server
  VolumeMount:
    Properties:
      Device: /dev/vdb
      InstanceId: {Ref: Instance}
      VolumeId: {Ref: VolumeId}
    Type: AWS::EC2::VolumeAttachment
  Floating-IP:
    Properties:
      NetworkInterfaceId:
        Ref: PrimaryNetworkId
      InstanceId:
        Ref: Instance
      EIP:
        Ref: IpAddress
    Type: AWS::EC2::EIPAssociation
  WaitConditionInstance:
    DependsOn: Instance
    Properties:
      Handle: {Ref: WaitHandleInstance}
      Timeout: {Ref: StartupTimeout}
    Type: AWS::CloudFormation::WaitCondition
  WaitHandleInstance:
    Properties: {}
    Type: AWS::CloudFormation::WaitConditionHandle

