# Heat template to initialize the the volume and populates it
HeatTemplateFormatVersion: '2012-12-12'
Description: Jenkins Server Create Volumes
Outputs:
  VolumeId:
    Description: Volume ID
    Value:
     Fn::GetAtt: [Instance, VolumeId]
Parameters:
  VolumeName:
    Description: Name for the volume
    Type: String
  PrimaryNetworkId:
    Description: PrimaryNetworkId
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
  InstanceZone:
    Default: 'nova'
    Description: AvailabilityZone for this instance
    Type: String
  Flavor:
    Default: m1.small
    Description: Flavor to boot
    Type: String
  Image:
    Default: centos-7
    Description: Image of choice
    Type: String
  StartupTimeout:
    Default: '1700'
    Description: How long to wait on node coming up
    Type: Number
  VolumeSize:
    Default: '100'
    Description: Volume size for each EBS volume
    Type: Number
  BaseURL:
    Default: 'https://raw.githubusercontent.com/EMSL-MSC/heat-templates/master/cfn'
    Description: Base URL where other templates live.
    Type: String
  ExtraUserData:
    Default: ''
    Description: Extra User Data
    Type: String
Resources:
  Instance:
    Properties:
      Parameters:
        Name: {Ref: VolumeName}
        Mnt: "/srv"
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        KeyName: {Ref: KeyName}
        InstanceZone: {Ref: InstanceZone}
        Flavor: {Ref: Flavor}
        Image: {Ref: Image}
        StartupTimeout: {Ref: StartupTimeout}
        VolumeSize: {Ref: VolumeSize}
        VolumeContainer: lvm
        VolumeFormat: ext4
        ExtraUserData:
          Fn::Base64:
            Fn::Replace:
              - "@EXTRAUSERDATA@": {Ref: ExtraUserData}
              - |
                mkdir -p /srv/jenkins/log
                mkdir -p /srv/jenkins/lib
                curl -o /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
                rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
                yum install -y java-1.7.0-openjdk-headless jenkins
                chown --recursive jenkins.jenkins /srv/jenkins
                chmod --recursive 770 /srv/jenkins/
                mount --bind /srv/jenkins/log /var/log/jenkins/
                mount --bind /srv/jenkins/lib /var/lib/jenkins/
                systemctl start jenkins
                sleep 60
                export JENKINS_URL=http://127.0.0.1:8080
                curl -o jenkins-cli.jar http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
                java -jar jenkins-cli.jar install-plugin git
                java -jar jenkins-cli.jar install-plugin jclouds-jenkins
                java -jar jenkins-cli.jar shutdown || true
                sleep 30
                ## Extra userdata
                @EXTRAUSERDATA@
                umount /var/log/jenkins/
                umount /var/lib/jenkins/
      TemplateURL:
          Fn::Join:
          - ''
          - - {Ref: BaseURL}
            - "/lib/Volume-Init.yaml"
    Type: AWS::CloudFormation::Stack
