HeatTemplateFormatVersion: '2012-12-12'
Description: Example Jenkins Server
Outputs:
  Name:
    Description: Name of instance
    Value:
      Fn::GetAtt: [Instance, Outputs.Name]
Parameters:
  PrimaryNetworkId:
    Default: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    Description: PrimaryNetworkId
    Type: String
  KeyName:
    Default: 'xxx'
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
  VolumeId: 
    Default: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    Description: Id of an existing volume for state
    Type: String
  FloatingIpAddress:
    Default: 'xxx.xxx.x.xx'
    Description: Floating Ip Address to assign
    Type: String
  Name:
    Default: 'testdb'
    Description: Name of the server
    Type: String
  DNSName:
    Default: 'testdb.example.com'
    Description: DNS Name of the server
    Type: String
  InstanceZone:
    Default: 'nova'
    Description: AvailabilityZone for this instance
    Type: String
  Flavor:
    Default: 'm1.large'
    Description: Flavor to boot
    Type: String
  Image:
    Default: 'centos-7'
    Description: Image of choice
    Type: String

Resources:
  Instance:
    Properties:
      Parameters:
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        KeyName: {Ref: KeyName}
        VolumeId: {Ref: VolumeId}
        FloatingIpAddress: {Ref: FloatingIpAddress}
        Name: {Ref: Name}
        DNSName: {Ref: DNSName}
        InstanceZone: {Ref: InstanceZone}
        Flavor: {Ref: Flavor}
        Image: {Ref: Image}
        AssignFloatingIp: "True"
        ExtraUserData: ""
      TemplateURL: 'https://raw.githubusercontent.com/EMSL-MSC/heat-templates/master/cfn/Jenkins/Jenkins.yaml'
    Type: AWS::CloudFormation::Stack
