HeatTemplateFormatVersion: '2012-12-12'
Description: MonboDB replica set
Mappings:
  AWSInstanceType2Arch:
    m1.large: {Arch: '64'}
    m1.medium: {Arch: '64'}
    m1.small: {Arch: '64'}
    m1.tiny: {Arch: '64'}
    m1.xlarge: {Arch: '64'}
  DistroArch2AMI:
    F17: {32: F17-i386-cfntools, 64: F17-x86_64-cfntools}
    F18: {32: F18-i386-cfntools, 64: F18-x86_64-cfntools}
    RHEL-6.1: {32: rhel61-i386-cfntools, 64: rhel61-x86_64-cfntools}
    RHEL-6.2: {32: rhel62-i386-cfntools, 64: rhel62-x86_64-cfntools}
    RHEL-6.3: {32: rhel63-i386-cfntools, 64: rhel63-x86_64-cfntools}
    SL6: {32: NOT IMPLEMENTED, 64: SL-6.4-x86_64-cfntools}
    U10: {32: U10-i386-cfntools, 64: U10-x86_64-cfntools}
Outputs:
  ReplicaSetMemberName1:
    Description: public DNS name of the MongoDB replica set member
      1
    Value:
      Fn::GetAtt: [ReplicaSetMember1, Outputs.ReplicaSetMemberName]
  ReplicaSetMemberName2:
    Description: public DNS name of the MongoDB replica set member
      2
    Value:
      Fn::GetAtt: [ReplicaSetMember2, Outputs.ReplicaSetMemberName]
Parameters:
  ClusterName:
    Description: Cluster Name
    Type: String
  BackendNetworkId: {Description: BackendNetworkId,
    Type: String}
  BackendSubnetId: {Description: BackendSubnetId,
    Type: String}
  InstanceType:
    AllowedValues: [m1.tiny, m1.small, m1.large, m1.xlarge, m2.xlarge,
      m2.2xlarge, m2.4xlarge, c1.xlarge, cc1.4xlarge, k1.large]
    Default: m1.large
    Description: EC2 instance type (e.g. m1.large, m1.xlarge, m2.xlarge)
    Type: String
  InstanceZone: {Description: AvailabilityZone for
      this instance, Type: String}
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access, Type: String}
  MongoDBYumRepo: {Description: Mongo DB Yum Repo,
    Default: 'http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/',
    Type: String}
  LinuxDistribution:
    AllowedValues: [SL6, F18, F17, U10, RHEL-6.1, RHEL-6.2, RHEL-6.3]
    Default: SL6
    Description: Distribution of choice
    Type: String
  PrimaryNetworkId: {Description: PrimaryNetworkId,
    Type: String}
  PrimarySecurityGroup: {Description: Primary MongoDB
      security group name, Type: String}
  BackendSecurityGroup: {Description: Backend MongoDB
      security group name, Type: String}
  TemplateBaseUrl: {Description: URL for templates,
    Type: String}
  ReplicaSetName: {Description: Name of the MongoDB
      replica set, Type: String}
  VolumeSize: {Default: '40', Description: Volume
      size for each EBS volume, Type: Number}
  ReplicaSet1ExtraUserData: {Default: '', Description: Extra
      UserData script, Type: String}
Resources:
  ReplicaSetSvrGroup:
    Properties:
      name: ReplicaSetSrvGroupAntiAffinity
      policies: [ 'anti-affinity' ]
    Type: OS::Nova::ServerGroup
  ReplicaSetPort1:
    Properties:
      name:
        Fn::Join:
          - ''
          - - {Ref: ClusterName}
            - '-'
            - {Ref: ReplicaSetName}
            - '-BackendPort1'
      network_id: {Ref: BackendNetworkId}
      fixed_ips:
        - {Ref: BackendSubnetId}
      security_groups:
      - {Ref: BackendSecurityGroup}
    Type: OS::Neutron::Port
  ReplicaSetPort2:
    Properties:
      name:
        Fn::Join:
          - ''
          - - {Ref: ClusterName}
            - '-'
            - {Ref: ReplicaSetName}
            - '-BackendPort2'
      network_id: {Ref: BackendNetworkId}
      fixed_ips:
        - {Ref: BackendSubnetId}
      security_groups:
      - {Ref: BackendSecurityGroup}
    Type: OS::Neutron::Port
  ReplicaSetMember1:
    Properties:
      Parameters:
        ClusterName: {Ref: ClusterName}
        SvrId: '1'
        MongoDBYumRepo: {Ref: MongoDBYumRepo}
        BackendPortId: {Ref: BackendPortId}
        ExtraUserData:
          Fn::Join:
          - ''
          - - "## Create replica set configuration\n"
            - "## The following is only needed on the PRIMARY\n"
            - "HOSTNAME=`/sbin/ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | "
            - "awk '{print $1}'`\n"
            - "cat <<EOF > /tmp/replicaSetConfigInit.js\n"
            - "config = {_id: \""
            - {Ref: ReplicaSetName}
            - "\", members : ["
            - "{_id : 0, host:\"$HOSTNAME:27017\"},"
            - "{_id : 1, host:\""
            - Fn::Select:
              - ip_address
              - Fn::Select:
                - '0'
                - Fn::GetAtt: [ReplicaSetPort2, fixed_ips]
            - ":27017\"}"
            - "]};\n"
            - "rs.initiate(config);\n"
            - "EOF\n"
            - "## Waiting until mongods have started\n"
            - "until nc -z $HOSTNAME 27017 ; do sleep 1 ; done\n"
            - "until nc -z "
            - Fn::Select:
              - ip_address
              - Fn::Select:
                - '0'
                - Fn::GetAtt: [ReplicaSetPort2, fixed_ips]
            - " 27017 ; do sleep 1 ; done\n"
            - "/usr/bin/mongo /tmp/replicaSetConfigInit.js > /tmp/replica-setup.log 2>&1\n"
            - {Ref: ReplicaSet1ExtraUserData}
        PrimarySecurityGroup: {Ref: PrimarySecurityGroup}
        InstanceType: {Ref: InstanceType}
        InstanceZone: {Ref: InstanceZone}
        KeyName: {Ref: KeyName}
        SchedulerGroup: {Ref: ReplicaSetSvrGroup}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        ReplicaSetName: {Ref: ReplicaSetName}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        ReplicaSetName: {Ref: ReplicaSetName}
        VolumeSize: {Ref: VolumeSize}
      TemplateURL:
        Fn::Join:
        - ''
        - - {Ref: TemplateBaseUrl}
          - /MongoDB_ReplicaSetMember.yaml
    Type: AWS::CloudFormation::Stack
  ReplicaSetMember2:
    Properties:
      Parameters:
        ClusterName: {Ref: ClusterName}
        SvrId: '2'
        MongoDBYumRepo: {Ref: MongoDBYumRepo}
        BackendPortId: {Ref: BackendPortId}
        ExtraUserData: echo foo; echo bar
        InstanceType: {Ref: InstanceType}
        InstanceZone: {Ref: InstanceZone}
        KeyName: {Ref: KeyName}
        SchedulerGroup: {Ref: ReplicaSetSvrGroup}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        ReplicaSetName: {Ref: ReplicaSetName}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        ReplicaSetName: {Ref: ReplicaSetName}
        PrimarySecurityGroup: {Ref: PrimarySecurityGroup}
        VolumeSize: {Ref: VolumeSize}
      TemplateURL:
        Fn::Join:
        - ''
        - - {Ref: TemplateBaseUrl}
          - /MongoDB_ReplicaSetMember.yaml
    Type: AWS::CloudFormation::Stack

