HeatTemplateFormatVersion: '2012-12-12'
Description: MonboDB replica set
Mappings:
  AWSInstanceType2Arch:
    m1.large: {Arch: '64'}
    m1.medium: {Arch: '64'}
    m1.small: {Arch: '64'}
    m1.tiny: {Arch: '64'}
    m1.xlarge: {Arch: '64'}
    k1.tiny: {Arch: '64'}
  DistroArch2AMI:
    F17: {32: F17-i386-cfntools, 64: F17-x86_64-cfntools}
    F18: {32: F18-i386-cfntools, 64: F18-x86_64-cfntools}
    RHEL-6.1: {32: rhel61-i386-cfntools, 64: rhel61-x86_64-cfntools}
    RHEL-6.2: {32: rhel62-i386-cfntools, 64: rhel62-x86_64-cfntools}
    RHEL-6.3: {32: rhel63-i386-cfntools, 64: rhel63-x86_64-cfntools}
    SL6: {32: NOT IMPLEMENTED, 64: SL-6.4-x86_64-cfntools}
    U10: {32: U10-i386-cfntools, 64: U10-x86_64-cfntools}
Outputs:
  ConfigSvr1:
    Description: public DNS name of the MongoDB config server 1
    Value:
      Fn::GetAtt: [ConfigSvr1, Outputs.ConfigSvrName]
  ConfigSvr2:
    Description: public DNS name of the MongoDB config server 2
    Value:
      Fn::GetAtt: [ConfigSvr2, Outputs.ConfigSvrName]
  ConfigSvr3:
    Description: public DNS name of the MongoDB config server 3
    Value:
      Fn::GetAtt: [ConfigSvr3, Outputs.ConfigSvrName]
Parameters:
  ClusterName:
    Description: Cluster Name
    Type: String
  TemplateBaseUrl: {Description: URL for templates,
    Type: String}
  PrimarySecurityGroup: {Description: Primary Security
      Group, Type: String}
  BackendSecurityGroup: {Description: Backend Security
      Group, Type: String}
  ExtraUserData: {Default: '', Description: Extra
      UserData script, Type: String}
  BackendIpPrefix: {Default: 10.0.101, Description: Ip
      Prefix to use, Type: String}
  BackendNetworkId: {Description: BackendNetworkId,
    Type: String}
  BackendSubnetId: {Description: BackendSubnetId,
    Type: String}
  ConfigSvr1IpPart: {Default: '7', Description: Ip
      suffix to use, Type: String}
  ConfigSvr2IpPart: {Default: '8', Description: Ip
      suffix to use, Type: String}
  ConfigSvr3IpPart: {Default: '9', Description: Ip
      suffix to use, Type: String}
  MongoDBYumRepo: {Description: Mongo DB Yum Repo,
    Default: 'http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/',
    Type: String}
  InstanceType:
    AllowedValues: [m1.tiny, m1.small, m1.large, m1.xlarge, m2.xlarge,
      m2.2xlarge, m2.4xlarge, c1.xlarge, cc1.4xlarge, k1.tiny]
    Default: m1.tiny
    Description: EC2 instance type (e.g. m1.large, m1.xlarge, m2.xlarge)
    Type: String
  InstanceZone: {Description: AvailabilityZone for
      this instance, Type: String}
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access, Type: String}
  LinuxDistribution:
    AllowedValues: [SL6, F18, F17, U10, RHEL-6.1, RHEL-6.2, RHEL-6.3]
    Default: SL6
    Description: Distribution of choice
    Type: String
  PrimaryNetworkId: {Description: PrimaryNetworkId,
    Type: String}
  VolumeSize: {Default: '2', Description: Volume
      size for each EBS volume, Type: Number}
Resources:
  ConfigSrvGroup:
    Properties:
      name: ConfigSrvGroupAntiAffinity
      policies: [ 'anti-affinity' ]
    Type: OS::Nova::ServerGroup
  ConfigSvr1:
    Properties:
      Parameters:
        ClusterName: {Ref: ClusterName}
        SvrId: '1'
        MongoDBYumRepo: {Ref: MongoDBYumRepo}
        BackendIpAddress:
          Fn::Join:
          - ''
          - - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr1IpPart}
        BackendNetworkId: {Ref: BackendNetworkId}
        BackendSubnetId: {Ref: BackendSubnetId}
        InstanceType: {Ref: InstanceType}
        InstanceZone: {Ref: InstanceZone}
        KeyName: {Ref: KeyName}
        SchedulerHints: { "group": { Ref: ConfigSrvGroup } }
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        PrimarySecurityGroup: {Ref: PrimarySecurityGroup}
        BackendSecurityGroup: {Ref: BackendSecurityGroup}
        VolumeSize: {Ref: VolumeSize}
        ExtraUserData:
          Fn::Join:
          - ''
          - - "CONFIGSVR1="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr1IpPart}
            - "\n"
            - "CONFIGSVR2="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr2IpPart}
            - "\n"
            - "CONFIGSVR3="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr3IpPart}
            - "\n"
            - {Ref: ExtraUserData}
            - "\n"
      TemplateURL:
        Fn::Join:
        - ''
        - - {Ref: TemplateBaseUrl}
          - /MongoDB_ConfigSvr.yaml
    Type: AWS::CloudFormation::Stack
  ConfigSvr2:
    Properties:
      Parameters:
        ClusterName: {Ref: ClusterName}
        SvrId: '2'
        MongoDBYumRepo: {Ref: MongoDBYumRepo}
        BackendIpAddress:
          Fn::Join:
          - ''
          - - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr2IpPart}
        BackendNetworkId: {Ref: BackendNetworkId}
        BackendSubnetId: {Ref: BackendSubnetId}
        InstanceType: {Ref: InstanceType}
        InstanceZone: {Ref: InstanceZone}
        KeyName: {Ref: KeyName}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        PrimarySecurityGroup: {Ref: PrimarySecurityGroup}
        BackendSecurityGroup: {Ref: BackendSecurityGroup}
        VolumeSize: {Ref: VolumeSize}
        ExtraUserData:
          Fn::Join:
          - ''
          - - "CONFIGSVR1="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr1IpPart}
            - "\n"
            - "CONFIGSVR2="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr2IpPart}
            - "\n"
            - "CONFIGSVR3="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr3IpPart}
            - "\n"
            - {Ref: ExtraUserData}
            - "\n"
      TemplateURL:
        Fn::Join:
        - ''
        - - {Ref: TemplateBaseUrl}
          - /MongoDB_ConfigSvr.yaml
    Type: AWS::CloudFormation::Stack
  ConfigSvr3:
    Properties:
      Parameters:
        ClusterName: {Ref: ClusterName}
        SvrId: '3'
        MongoDBYumRepo: {Ref: MongoDBYumRepo}
        BackendIpAddress:
          Fn::Join:
          - ''
          - - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr3IpPart}
        BackendNetworkId: {Ref: BackendNetworkId}
        BackendSubnetId: {Ref: BackendSubnetId}
        InstanceType: {Ref: InstanceType}
        InstanceZone: {Ref: InstanceZone}
        KeyName: {Ref: KeyName}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        PrimarySecurityGroup: {Ref: PrimarySecurityGroup}
        BackendSecurityGroup: {Ref: BackendSecurityGroup}
        VolumeSize: {Ref: VolumeSize}
        ExtraUserData:
          Fn::Join:
          - ''
          - - "CONFIGSVR1="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr1IpPart}
            - "\n"
            - "CONFIGSVR2="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr2IpPart}
            - "\n"
            - "CONFIGSVR3="
            - {Ref: BackendIpPrefix}
            - .
            - {Ref: ConfigSvr3IpPart}
            - "\n"
            - {Ref: ExtraUserData}
            - "\n"
      TemplateURL:
        Fn::Join:
        - ''
        - - {Ref: TemplateBaseUrl}
          - /MongoDB_ConfigSvr.yaml
    Type: AWS::CloudFormation::Stack

