HeatTemplateFormatVersion: '2012-12-12'
Description: Management Server Create Volumes
Outputs:
  FixedIps:
    Description: Neutron Port Fixed IPs
    Value:
      Fn::GetAtt: [Instance, Outputs.FixedIps]
  VolumeId:
    Description: Volume ID
    Value:
      Fn::GetAtt: [Instance, Outputs.VolumeId]
Parameters:
  Name: {Default: 'Mgmt', Description: Name for the volume, Type: String}
  PrimaryNetworkId: {Description: PrimaryNetworkId, Type: String}
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access, Type: String}
  ExtraUserData: {Default: '', Description: Extra
      UserData script, Type: String}
  InstanceZone: {Default: 'nova', Description: AvailabilityZone for
      this instance, Type: String}
  Flavor:
    Default: m1.tiny
    Description: Flavor to boot
    Type: String
  Image:
    Default: centos-6.5
    Description: Image of choice
    Type: String
  StartupTimeout: {Default: '1700', Description: How
      long to wait on node coming up, Type: Number}
  VolumeSize: {Default: '1', Description: Volume
      size for each EBS volume, Type: Number}
Resources:
  Instance:
    Properties:
      Parameters:
        Name: {Ref: Name}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        KeyName: {Ref: KeyName}
        InstanceZone: {Ref: InstanceZone}
        Flavor: {Ref: Flavor}
        Image: {Ref: Image}
        StartupTimeout: {Ref: StartupTimeout}
        VolumeSize: {Ref: VolumeSize}
        VolumeContainer: lvm
        VolumeFormat: ext4
        ExtraUserData:
          Fn::Base64:
            Fn::Join:
            - ''
            - - "if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then\n"
              - "    /etc/init.d/sshd start\n"
              - "fi\n"
              - "mkdir -p /srv/etc\n"
              - "mkdir -p /srv/home\n"
              - "cp -a /etc/ssh /srv/etc\n"
              - "mkdir -p /srv/root/.ssh/\n"
              - "ssh-keygen -N '' -f /srv/root/.ssh/id_rsa\n"
              - "## Extra userdata\n"
              - {Ref: ExtraUserData}
              - "\n"
      TemplateURL: 'https://raw.githubusercontent.com/EMSL-MSC/heat-templates/master/cfn/lib/Volume-Init.yaml'
    Type: AWS::CloudFormation::Stack

