HeatTemplateFormatVersion: '2012-12-12'
Description: Trac Server
Outputs:
  Name:
    Description: public DNS name of the Trac Server
      Instance
    Value:
      Fn::Select:
      - ip_address
      - Fn::Select:
        - '0'
        - Fn::GetAtt: [BackendInterface, fixed_ips]
  Id:
    Description: Instance Id
    Value:
      Ref: Instance
Parameters:
  Name: {Description: ServerName, Type: String}
  IpAddress: {Description: Floating Ip Address to assign, Type: String}
  VolumeId: {Description: Volume where data lives, Type: String}
  PrimarySecurityGroup: {Description: Primary Security Group, Type: String}
  ExtraUserData: {Default: '', Description: Extra UserData script, Type: String}
  InstanceType:
    Default: m1.tiny
    Description: EC2 instance type (e.g. m1.large, m1.xlarge, m2.xlarge)
    Type: String
  InstanceZone:
    Default: nova
    Description: AvailabilityZone for this instance
    Type: String
  KeyName: {Description: Name of an existing EC2 KeyPair to enable SSH access, Type: String}
  Image: {Description: Image to use, Type: String}
  PrimaryNetworkId: {Description: PrimaryNetworkId, Type: String}
  StartupTimeout: {Default: '700', Description: How long to wait on node coming up, Type: Number}
Resources:
  PrimaryInterface:
    Properties:
      name:
        Fn::Join:
        - ''
        - - {Ref: Name}
          - -PrimaryPort
      network_id: {Ref: PrimaryNetworkId}
      security_groups:
      - {Ref: PrimarySecurityGroup}
    Type: OS::Neutron::Port
  Instance:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              git: []
              trac: []
              httpd: []
              mod_ssl: []
              mod_wsgi: []
              trac-git-plugin: []
    Properties:
      name:
        Fn::Join:
        - ''
        - - {Ref: Name}
      availability_zone: {Ref: InstanceZone}
      image: {Ref: Image}
      flavor: {Ref: InstanceType}
      key_name: {Ref: KeyName}
      networks:
      - port: {Ref: PrimaryInterface}
      user_data:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - "yum update -y aws-cfn-bootstrap\n"
            - "## Error reporting helper function\n"
            - "function error_exit\n"
            - "{\n"
            - "   /opt/aws/bin/cfn-signal -e 1 -r \"$1\" '"
            - {Ref: WaitHandleServer}
            - "'\n"
            - "   exit 1\n"
            - "}\n"
            - "function trap_error\n"
            - "{\n"
            - "	error_exit \"Line: ${BASH_LINENO[0]}, ExitCode: $1\"\n"
            - "}\n"
            - "set -eu\n"
            - "trap 'trap_error \"$?\"' ERR\n"
            - "## Initialize CloudFormation bits\n"
            - "/opt/aws/bin/cfn-init -s "
            - {Ref: "AWS::StackName"}
            - " -r Instance --region "
            - {Ref: "AWS::Region"}
            - " > /tmp/cfn-init.log 2>&1 || error_exit $(</tmp/cfn-init.log)\n"
            - "while [ ! -e /dev/vdb ]; do echo waiting for /dev/vdb to attach; sleep 10; done\n"
            - "/etc/init.d/sshd stop || true \n"
            - "echo '/dev/trac-vg0/trac-data /srv ext4 defaults,auto,noatime,noexec 0 0'"
            - " | tee -a /etc/fstab\n"
            - "mount /srv\n"
            - "mv /etc/ssh /etc/ssh.orig\n"
            - "ln -s /srv/etc/ssh /etc/ssh\n"
            - "if [ ! -f /srv/root/.ssh/authorized_keys.orig ]; then\n"
            - "    mv /srv/root/.ssh/authorized_keys /srv/root/.ssh/authorized_keys.orig || true\n"
            - "    cp -af /root/.ssh/authorized_keys /srv/root/.ssh\n"
            - "fi\n"
            - "cp -af /root/.ssh/authorized_keys /srv/root/.ssh\n"
            - "rm -rf /root/.ssh\n"
            - "ln -s /srv/root/.ssh /root/.ssh\n"
            - "trac-admin /srv/trac deploy /tmp/deploy\n"
            - "rm -rf /srv/trac/cgi-bin\n"
            - "rm -rf /srv/trac/htdocs\n"
            - "mv -f /tmp/deploy/* /srv/trac\n"
            - "export NAME=`grep '^name[ ]*=' /srv/trac/conf/trac.ini | sed 's/^name[ ]*=[ ]*//'`\n"
            - "cat > /etc/httpd/conf.d/trac.conf << EOF\n"
            - "RewriteEngine On\n"
            - "RewriteCond %{HTTPS} !=on\n"
            - "RewriteRule ^/?(.*) https://%{SERVER_NAME}/\\$1 [R,L]\n"
            - "RedirectMatch ^/$ /trac/\n"
            - "Alias /trac/chrome/common /srv/trac/htdocs/common\n"
            - "Alias /trac/chrome/site /srv/trac/htdocs/site\n"
            - "WSGIScriptAlias /trac /srv/trac/cgi-bin/trac.wsgi\n"
            - '<Directory "/srv/trac/htdocs">'
            - "\n"
            - "  Order allow,deny\n"
            - "  Allow from all\n"
            - "</Directory>\n"
            - '<Directory "/srv/trac/cgi-bin">'
            - "\n"
            - "  WSGIApplicationGroup %{GLOBAL}\n"
            - "  Order allow,deny\n"
            - "  Allow from all\n"
            - "</Directory>\n"
            - "SetEnv GIT_PROJECT_ROOT /srv/git\n"
            - "SetEnv GIT_HTTP_EXPORT_ALL\n"
            - "ScriptAliasMatch ^(/.*?)(\\.git)(/.*)?\\$ /usr/libexec/git-core/git-http-backend/\\$3\n"
            - "<LocationMatch \"^(/.*?)(\\.git)(/.*)?\\$\">\n"
            - "   include /srv/trac/apache-access.conf\n"
            - "</LocationMatch>\n"
            - "<Directory \"/usr/libexec/git-core\">\n"
            - "  Options +ExecCGI -Includes\n"
            - "  Order allow,deny\n"
            - "  Allow from all\n"
            - "</Directory>\n"
            - "<Location /trac/login>\n"
            - "   include /srv/trac/apache-access.conf\n"
            - "</Location>\n"
            - "EOF\n"
            - "if [ -n /srv/trac/apache-access.conf ]; then\n"
            - "   cat > /srv/trac/apache-access.conf << EOF\n"
            - "AuthType Basic\n"
            - "AuthName \"Login\"\n"
            - "AuthUserFile /srv/trac/htpasswd\n"
            - "Require valid-user\n"
            - "EOF\n"
            - "fi\n"
            - "mkdir -p /srv/certs\n"
            - "if [ -n /srv/certs/localhost.key ]; then\n"
            - "   mv /etc/pki/tls/private/localhost.key /srv/certs/localhost.key\n"
            - "fi\n"
            - "if [ -n /srv/certs/localhost.crt ]; then\n"
            - "   mv /etc/pki/tls/certs/localhost.crt /srv/certs/localhost.crt\n"
            - "fi\n"
            - "rm -f /etc/pki/tls/certs/localhost.crt /etc/pki/tls/private/localhost.key\n"
            - "ln -s /srv/certs/localhost.key /etc/pki/tls/private/localhost.key\n"
            - "ln -s /srv/certs/localhost.crt /etc/pki/tls/certs/localhost.crt\n"
            - "## Extra userdata\n"
            - {Ref: ExtraUserData}
            - "\n"
            - "chkconfig httpd on\n"
            - "service httpd start\n"
            - "## CloudFormation signal that setup is complete\n"
            - "/opt/aws/bin/cfn-signal -e 0 -r \"Server setup complete\" '"
            - {Ref: WaitHandleServer}
            - "'\n"
    Type: OS::Nova::Server
  VolumeMount:
    Properties:
      Device: /dev/vdb
      InstanceId: {Ref: Instance}
      VolumeId: {Ref: VolumeId}
    Type: AWS::EC2::VolumeAttachment
  Floating-IP:
    Properties:
      NetworkInterfaceId:
        Ref: PrimaryNetworkId
      InstanceId:
        Ref: Instance
      EIP:
        Ref: IpAddress
    Type: AWS::EC2::EIPAssociation
  WaitConditionServer:
    DependsOn: Instance
    Properties:
      Handle: {Ref: WaitHandleServer}
      Timeout: {Ref: StartupTimeout}
    Type: AWS::CloudFormation::WaitCondition
  WaitHandleServer:
    Properties: {}
    Type: AWS::CloudFormation::WaitConditionHandle

