HeatTemplateFormatVersion: '2012-12-12'
Description: Trac Server Create Volumes
Parameters:
  Name: {Default: 'Trac', Description: Name for the volume, Type: String}
  PrimaryNetworkId: {Description: PrimaryNetworkId, Type: String}
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access, Type: String}
  ExtraUserData: {Default: '', Description: Extra
      UserData script, Type: String}
  InstanceZone: {Default: 'nova', Description: AvailabilityZone for
      this instance, Type: String}
  Flavor:
    Default: m1.tiny
    Description: Flavor to boot
    Type: String
  Image:
    Default: centos-6.5
    Description: Image of choice
    Type: String
  StartupTimeout: {Default: '1700', Description: How
      long to wait on node coming up, Type: Number}
  VolumeSize: {Default: '1', Description: Volume
      size for each EBS volume, Type: Number}
  AdminUsername:
      Default: 'admin'
      Description: Admin Username
      Type: String
  AdminPassword:
      Default: 'changeme'
      Description: Admin Password
      Type: String
      NoEcho: True
Resources:
  Instance:
    Properties:
      Parameters:
        Name: {Ref: Name}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        KeyName: {Ref: KeyName}
        InstanceZone: {Ref: InstanceZone}
        Flavor: {Ref: Flavor}
        Image: {Ref: Image}
        StartupTimeout: {Ref: StartupTimeout}
        VolumeSize: {Ref: VolumeSize}
        VolumeContainer: lvm
        VolumeFormat: ext4
        ExtraUserData:
          Fn::Base64:
            Fn::Join:
            - ''
            - - "if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then\n"
              - "    /etc/init.d/sshd start\n"
              - "fi\n"
              - "mkdir -p /srv/etc\n"
              - "mkdir -p /srv/trac\n"
              - "mkdir -p /srv/git\n"
              - "yum install -y trac git\n"
              - "git init --bare /srv/git\n"
              - "pushd /srv/git; git update-server-info; popd\n"
              - "chown --recursive apache.apache /srv/git\n"
              - "curl http://trac-hacks.org/raw-attachment/wiki/GitPlugin/trac-post-receive-hook-0.12-new-commits-from-all-branches-with-logfile.py > /srv/git/hooks/trac.py\n"
              - "cp -a /etc/ssh /srv/etc\n"
              - "mkdir -p /srv/root/.ssh/\n"
              - "ssh-keygen -N '' -f /srv/root/.ssh/id_rsa\n"
              - "(echo '"
              - {Ref: "AWS::StackName"}
              - "'; echo '') | trac-admin /srv/trac/ initenv\n"
              - "sed 's/\\(repository_type[ ]*=[ ]*\\).*/\\1git/' -i /srv/trac/conf/trac.ini\n"
              - "sed 's/\\(repository_dir[ ]*=[ ]*\\).*/\\1\\/srv\\/git/' -i /srv/trac/conf/trac.ini\n"
              - "sed -i \"s/\\(TRAC_ENV[ ]*=[ ]*\\).*/\\1'\\/srv\\/trac'/\" /srv/git/hooks/trac.py\n"
              - "sed -i \"s/\\(TRAC_ADMIN[ ]*=[ ]*\\).*/\\1'\\/usr\\/bin\\/trac-admin'/\" /srv/git/hooks/trac.py\n"
              - "sed -i \"s/\\(LOG_FILE[ ]*=[ ]*\\).*/\\1'\\/srv\\/trac\\/tracgitplugin.log'/\" /srv/git/hooks/trac.py\n"
              - "cat >> /srv/trac/conf/trac.ini << \"EOF\"\n"
              - "[components]\n"
              - "tracext.git.* = enabled\n"
              - "tracopt.ticket.commit_updater.committicketreferencemacro = enabled\n"
              - "tracopt.ticket.commit_updater.committicketupdater = enabled\n"
              - "EOF\n"
              - "chown -R apache.apache /srv/trac\n"
              - "echo 1 > /srv/trac/.v\n"
              - "tracd --version | awk '{print $2}' > /srv/trac/.v2\n"
              - "htpasswd -bc /srv/trac/htpasswd \""
              - {Ref: AdminUsername}
              - "\" \""
              - {Ref: AdminPassword}
              - "\"\n"
              - "trac-admin /srv/trac permission add \""
              - {Ref: AdminUsername}
              - "\" TRAC_ADMIN\n"
              - "## Extra userdata\n"
              - {Ref: ExtraUserData}
              - "\n"
      TemplateURL: 'https://raw.github.com/EMSL-MSC/heat-templates/master/cfn/lib/Volume-Init.yaml'
    Type: AWS::CloudFormation::Stack

