HeatTemplateFormatVersion: '2012-12-12'
Description: Database
Parameters:
  PrimaryNetworkId: 
    Description: PrimaryNetworkId
    Type: String
  Name:
    Description: Name of the server
    Type: String
  DNSName:
    Description: DNS Name of the server
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
  InstanceZone:
    Description: AvailabilityZone for this instance
    Type: String
  Flavor:
    Default: m1.large
    Description: Flavor to boot
    Type: String
  Image:
    Default: centos-7
    Description: Image of choice
    Type: String
  StartupTimeout: 
    Default: 2400
    Description: How long to wait on node coming up
    Type: Number
  VolumeId:
    Description: Volume Id
    Type: String
  VolumeName:
    Description: Volume Name
    Type: String
  AssignFloatingIp:
    AllowedValues: ["True", "False"]
    Default: "False"
    Description: Use true to setup a floating ip
    Type: String
  FloatingIpAddress:
    Default: "-1"
    Description: The floating ip address you would like to attach
    Type: String
  FloatingIpId:
    Default: '-1'
    Description: The floating ip id
    Type: String
  FloatingIpType:
    AllowedValues: ["instance_ip", "port_id"]
    Default: "instance_ip"
    Description: How to configure. instance_ip or port_id.
    Type: String
  BaseURL:
    Default: 'https://raw.githubusercontent.com/EMSL-MSC/heat-templates/master/cfn/lib'
    Description: Base URL where other templates live.
    Type: String
  ExtraUserData:
    Default: ''
    Description: Extra User Data
    Type: String
Resources:
  Instance:
    Properties:
      Parameters:
        Name: {Ref: Name}
        PrimaryNetworkId: {Ref: PrimaryNetworkId}
        Image: {Ref: Image}
        Flavor: {Ref: Flavor}
        InstanceZone: {Ref: InstanceZone}
        CreateSecurityGroup: "True"
        SecurityGroupSimplePorts: "22,3306,5432"
        AssignVolume: "True"
        VolumeId: {Ref: VolumeId}
        VolumeName: {Ref: VolumeName}
        AssignFloatingIp: {Ref: AssignFloatingIp}
        FloatingIpId: {Ref: FloatingIpId}
        FloatingIpType: {Ref: FloatingIpType}
        FloatingIpAddress: {Ref: FloatingIpAddress}
        KeyName: {Ref: KeyName}
        BaseURL: {Ref: BaseURL}
        ExtraUserData:
          Fn::Replace:
            - "@DNSNAME@": {Ref: DNSName}
              "@NAME@": {Ref: Name}
              "@EXTRAUSERDATA@": {Ref: ExtraUserData}
            - |

              hostname @DNSNAME@
              sed -i 's/HOSTNAME=.*/HOSTNAME='@DNSNAME@'/' /etc/sysconfig/network
              hostnamectl set-hostname --static @DNSNAME@ || true

              ntpdate ntp.ubuntu.com || true
              systemctl enable ntpdate || chkconfig ntpdate on || true
              systemctl start ntpdate || service ntpdate start || true
              sed -i 's/SELINUX=.*/SELINUX=permissive/' /etc/sysconfig/selinux || true
              setenforce Permissive || true

              if [ -d /srv/postgresql ]; then
                  yum install -y postgresql postgresql-server

                  mv /var/lib/pgsql /var/lib/pgsql.old
                  ln -s /srv/postgresql/lib /var/lib/pgsql
              fi

              if [ -d /srv/mysql ]; then
                  yum install -y mysql mariadb-galera-server

                  mv /var/lib/mysql /var/lib/mysql.old
                  ln -s /srv/mysql/lib /var/lib/mysql
              fi

              ## Extra userdata
              @EXTRAUSERDATA@

              if [ -d /srv/postgresql ]; then
                  systemctl enable postgresql || chkconfig postgresql on
                  systemctl start postgresql || service start postgresql
              fi

              if [ -d /srv/mysql ]; then
                  systemctl enable mysqld || shkconfig mysqld on
                  systemctl start mysqld || service start mysqld
              fi
      TemplateURL:
          Fn::Join:
          - ''
          - - {Ref: BaseURL}
            - "/SimpleServer.yaml"
    Type: AWS::CloudFormation::Stack
